spring.application.name=hello-spring-k8s
management.endpoints.web.exposure.include=*
db.server.address=hhtest.lhrtt.cn
db.server.port=6897
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://${db.server.address}:${db.server.port}/testk3s
spring.datasource.username=testk3s
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional Hikari Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
